### ISSUE TITLE
profiles limit cap, possible to add a scroll to the dropdown menu to allow higher barber profiles limit?

### ISSUE THREAD

**Issue by Chloe-Necri** [jyggen/BarberShopProfiles#2]
ello, 
as the title says, after about 50 - 60 profiles, it goes off the screen and thus unable to make more =(

is it possible to add a slider to the menu? <3

**Comment by jyggen** [comment]
This is now implemented in version 1.2.0. Sorry for the wait, I don't play WoW these days, so was a bit tricky to do without the ability to test it myself.
